sudo: required
services:
  - docker

branches:
  only:
    - master
  
script:
   - docker build -t zabbix .

deploy:
   provider: script
   script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make push-in
   on:
     branch: master

