sudo: required
services:
  - docker

branches:
  only:
    - master
  
script:
  - docker build -t zabbix .
  - docker ps
  - docker ps -a
  - docker images
  - echo $DOCKER_USERNAME
  - bash docker_push


